### ISSUE TITLE
Image is difficult to recognize

### ISSUE THREAD

**Issue by gnlup** [vishpbharadwaj/Lenet_arch#1]
Hi, could you please upload a high-definition picture of "microarch" ? The small print part is difficult to recognize even if I magnified the picture. Thank you very much!

**Comment by vishpbharadwaj** [comment]
[arch_simple.pdf](https://github.com/vishpbharadwaj/Lenet_arch/files/7776979/arch_simple.pdf)

Have attached a Visio converted to PDF. This can be magnified.
